// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcFlSpnq6Q90AvtwBY4N0lVxZhoheclqQ',
    appId: '1:56445493620:web:5ae903925108485f90cc21',
    messagingSenderId: '56445493620',
    projectId: 'buffedup-e5aa5',
    authDomain: 'buffedup-e5aa5.firebaseapp.com',
    storageBucket: 'buffedup-e5aa5.appspot.com',
    measurementId: 'G-NMT9JQX93T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtZEG2lheoFYf-2vMieQM2OT84asad7LI',
    appId: '1:56445493620:android:5b0005f32d20ee4890cc21',
    messagingSenderId: '56445493620',
    projectId: 'buffedup-e5aa5',
    storageBucket: 'buffedup-e5aa5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf4yGG_lwNGgncA0wUrdSyY2m3Go92UKo',
    appId: '1:56445493620:ios:3e58553469a12dd190cc21',
    messagingSenderId: '56445493620',
    projectId: 'buffedup-e5aa5',
    storageBucket: 'buffedup-e5aa5.appspot.com',
    iosBundleId: 'com.okayitssundar.buffedup',
  );
}
